package app.muplay.database

import java.nio.charset.StandardCharsets
import java.security.GeneralSecurityException
import javax.crypto.Cipher
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * AES-GCM sealing for credential material.
 *
 * The IV is generated fresh for every [seal] and prefixed to the ciphertext. Reusing an IV under
 * the same GCM key destroys both confidentiality and authenticity at once, so this is not a
 * detail — `everyy seal uses a fresh iv` in the test suite is the assertion that keeps it true.
 *
 * Takes a [SecretKey] rather than reaching for `AndroidKeyStore` itself, which is what makes the
 * whole contract testable in Tier 1; [CredentialStore] owns the key's lifetime.
 */
object KeystoreCipher {

  private const val IV_BYTES = 12
  private const val TAG_BITS = 128
  private const val TRANSFORMATION = "AES/GCM/NoPadding"

  /**
   * The IV is generated by the *provider*, never by this code, and that is a correctness
   * requirement rather than a style choice.
   *
   * An `AndroidKeyStore` AES-GCM key rejects a caller-supplied IV outright --
   * `InvalidAlgorithmParameterException: Caller-provided IV not permitted` -- unless the key was
   * created with `setRandomizedEncryptionRequired(false)`, which exists precisely to let callers
   * do the unsafe thing. Keystore generates a fresh random IV per operation itself; asking for
   * one is asking to be allowed to reuse it, and IV reuse under GCM with one key leaks the XOR of
   * the two plaintexts *and* the authentication key.
   *
   * This mattered in practice: the first version of this function passed its own IV, which the
   * JVM test suite accepted happily -- a software AES provider permits it -- and which failed on
   * a real device the moment [CredentialStore] used a real Keystore key. The unit tests are
   * genuinely useful for the cryptographic contract, but only the instrumented test exercises the
   * provider that ships.
   *
   * The wire format is unchanged: `iv || ciphertext || tag`, with the IV read back off the
   * cipher.
   */
  fun seal(key: SecretKey, plaintext: String): ByteArray {
    val cipher = Cipher.getInstance(TRANSFORMATION)
    cipher.init(Cipher.ENCRYPT_MODE, key)
    val iv = requireProviderIv(cipher.iv)
    return iv + cipher.doFinal(plaintext.toByteArray(StandardCharsets.UTF_8))
  }

  /**
   * [iv] unchanged, or [GeneralSecurityException] if the provider did not return the
   * [IV_BYTES]-byte nonce [open] assumes when it slices a fixed-length prefix back off. A
   * provider that chose a different GCM nonce length would otherwise corrupt every blob
   * silently.
   *
   * `internal` and separate from [seal] so it can be tested at all: every provider available on
   * either the JVM or a device returns 12 bytes for GCM, so the guard is unreachable through
   * [seal] itself. Leaving it inline meant an untestable branch, and this project does not lower
   * a coverage floor to accommodate code it chose not to make testable.
   */
  internal fun requireProviderIv(iv: ByteArray): ByteArray {
    if (iv.size != IV_BYTES) {
      throw GeneralSecurityException(
        "expected a $IV_BYTES-byte GCM IV from the provider but got ${iv.size}",
      )
    }
    return iv
  }

  fun open(key: SecretKey, sealed: ByteArray): String {
    if (sealed.size <= IV_BYTES) {
      throw GeneralSecurityException("sealed blob is too short to contain an IV")
    }
    val iv = sealed.copyOfRange(0, IV_BYTES)
    val ciphertext = sealed.copyOfRange(IV_BYTES, sealed.size)
    val cipher = Cipher.getInstance(TRANSFORMATION)
    cipher.init(Cipher.DECRYPT_MODE, key, GCMParameterSpec(TAG_BITS, iv))
    return String(cipher.doFinal(ciphertext), StandardCharsets.UTF_8)
  }
}
