#!/usr/bin/env bash
set -euo pipefail
#
# Derives the committed fixture oracle at core/testing/src/main/resources/fixtures/books.tsv from
# the committed audio files, using ffprobe.
#
# WHY THIS EXISTS AND WHY IT IS SEPARATE FROM seed-fixtures.sh
# ============================================================================================
# `ci/seed-fixtures.sh` *encodes*, and its output is bit-reproducible only for one ffmpeg version
# -- which is why the fixtures are committed binaries verified by `md5sum -c ci/fixtures.md5`
# rather than rebuilt in CI. This script only *reads*. Reading a `chpl`/`chap` atom or a stream
# duration is stable across ffprobe versions in a way that encoding is not, so this one CAN run in
# CI, and does.
#
# WHAT IT IS FOR. Task 3 asserts that Media3 reads the same chapters ffprobe reads. Two
# independent readers of the same bytes agreeing is an oracle. A test asserting Media3 returns
# whatever Media3 returned last time is not, and this project has been bitten repeatedly by
# assertions that execute without discriminating.
#
# USAGE:  ci/probe-chapters.sh           # regenerate the table
#         ci/probe-chapters.sh --check   # fail if the committed table no longer matches the files
#
# The table is tab-separated, two record kinds, and its ORDER IS PART OF THE ORACLE:
#   track    <path>   <durationMs>  <title>  <trackNumber>
#   chapter  <path>   <startMs>     <endMs>  <title>
# Tracks are emitted sorted by path; chapters are emitted in the order ffprobe lists them, which
# is the order they appear in the file. Task 3 asserts chapter order with `containsExactly`, so an
# oracle that sorted them would quietly destroy the only evidence of ordering there is.
#
# WHAT `durationMs` IS, EXACTLY, AND WHY THE MP3s ARE NOT ROUND NUMBERS
# ============================================================================================
# `format.duration`, in milliseconds. For the `.m4b` fixtures that is the round number
# `ci/seed-fixtures.sh` asked ffmpeg for (21000 / 15000 / 12000) because the mov muxer's edit list
# trims AAC priming delay. For the `.mp3` fixtures it is NOT: LAME pads to a whole 1152-sample
# frame and prepends an encoder delay, so a 4-second request lands at 155 frames = 4048.98 ms.
# The Xing/`Info` header records the delay and the padding, and both ffprobe and Media3's
# `Mp3Extractor` report the untrimmed frame span as the duration (the trim happens at the audio
# sink) -- so 4049, not 4000, is what BOTH readers say, which is the only property this oracle
# needs. Do not "fix" these to round numbers: there is no libmp3lame invocation that produces one.

cd "$(dirname "$0")/.."
FIXTURES="ci/fixtures"
TABLE="core/testing/src/main/resources/fixtures/books.tsv"

if ! command -v ffprobe > /dev/null; then
  echo "ffprobe not found. Install ffmpeg." >&2
  exit 2
fi
if ! command -v python3 > /dev/null; then
  echo "python3 not found." >&2
  exit 2
fi

# The JSON -> TSV step, kept in one place and handed the relative path as `argv[1]` rather than
# interpolated into the program text. A path is data: `Fourth Author/Multi Part Book/01 - Part
# One.mp3` happens to contain neither a quote nor a `%`, and the moment a fixture is added that
# does, a shell-interpolated version of this either fails to parse or silently mis-formats.
ROWS_PY='
import json, sys

rel = sys.argv[1]
d = json.load(sys.stdin)
# Container tags first, STREAM tags underneath them. An Ogg file keeps its Vorbis comment inside
# the logical stream, so `format.tags` is absent entirely for the `.opus` fixture while
# `streams[0].tags` carries title/artist/album/TRACKNUMBER -- measured, not assumed. mp3 and m4b
# put theirs on the container, so the container wins wherever both exist and nothing about the
# rows this script emitted before the Opus fixture arrived can move.
tags = dict(d["streams"][0].get("tags", {}))
tags.update(d["format"].get("tags", {}))

duration_ms = int(round(float(d["format"]["duration"]) * 1000))
title = tags.get("title", "")
track = int(str(tags.get("track", "0")).split("/")[0] or 0)
print("track\t%s\t%d\t%s\t%d" % (rel, duration_ms, title, track))

for c in d["chapters"]:
    tb_num, tb_den = (int(x) for x in c["time_base"].split("/"))
    start = int(round(int(c["start"]) * tb_num * 1000 / tb_den))
    end = int(round(int(c["end"]) * tb_num * 1000 / tb_den))
    print("chapter\t%s\t%d\t%d\t%s" % (rel, start, end, c.get("tags", {}).get("title", "")))
'

emit() {
  printf '# generated by ci/probe-chapters.sh -- do not hand-edit\n'
  printf '# kind\tpath\ta\tb\tc\n'
  find "$FIXTURES" -type f \( -name '*.mp3' -o -name '*.m4b' -o -name '*.opus' \) | LC_ALL=C sort | while read -r f; do
    rel="${f#"$FIXTURES"/}"
    ffprobe -v quiet -print_format json -show_format -show_streams -show_chapters "$f" \
      | python3 -c "$ROWS_PY" "$rel"
  done
}

if [ "${1:-}" = "--check" ]; then
  # Generated to a real file with its exit status checked, rather than into `<(emit)`: a process
  # substitution's failure is invisible to `set -e` and to `pipefail`, so an `emit` that died
  # halfway would reach `diff` as a truncated stream and be reported as "the oracle drifted" --
  # the right exit code for the wrong reason, and a diff nobody could act on.
  actual="$(mktemp)"
  trap 'rm -f "$actual"' EXIT
  emit > "$actual"

  if ! diff -u "$TABLE" "$actual"; then
    echo "" >&2
    echo "The committed chapter oracle no longer matches the committed audio fixtures." >&2
    echo "Either a fixture changed (regenerate the table: ci/probe-chapters.sh) or ffprobe" >&2
    echo "disagrees with what was recorded. Read the diff before doing either." >&2
    exit 1
  fi
  echo "chapter oracle matches the fixtures"
else
  mkdir -p "$(dirname "$TABLE")"
  emit > "$TABLE"
  echo "wrote $TABLE"
fi
